name: remind after every interval

on: 
  schedule:
    #- cron: "0 */6 * * *"
    - cron: "0,30 * * * *"
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run binary
        run: |
          chmod +x ./Elorts
          ./Elorts reminders -c ${{secrets.webhook}} -d ${{secrets.dweetrem}}
