name: check sites after interval

on: 
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run binary
        run: |
          chmod +x ./Elorts
          ./Elorts web-check -c ${{secrets.webhook}} -d ${{secrets.dweetweb1}} -i ${{secrets.dweetweb2}}
